baseURL = "https://css-ninja.netlify.com/"
languageCode = "en-us"
title = "Ajaj Rajguru | Front-End Developer | Goa | Personal Portfolio"
theme = "personal-web"
copyright="Ajaj Rajguru"
googleAnalytics = "UA-145062056-1"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Ajaj :wave:"
  sub = "I'm a Front-End Developer From Goa."

[params.keywords]
  tags = "UI, User interface, UX, User Experience, Front-end developer, Front end developer, Front-end, Front end, Designing, websites, CSS, CSS3, HTML, HTML5, jQuery, Javascript, Goa, Layouts, CMS, Static Site, Hugo"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "" - Portfolio Cover
  gradientOverlay = '' # default: to right bottom, #000000, #0b0820, #050858, #0b0820, #000000
  logo = "" # - default "/images/me.jpg"
  title = "My Face" # - default "Profile Pic"
[params.assets]
  favicon = "/images/fav.png"
  customCSS = ""

[params.social]
  github = ""
  twitter = "https://twitter.com/"
  linkedin = "https://www.linkedin.com/in/"
  medium = ""
  codepen = "https://codepen.io/"
  facebook = "https://www.facebook.com/"
  youtube = ""
  instagram = ""
  gitlab = ""
  keybase = ""

[params.contact]
  email = ""
  text= "Email" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog section"
  url = "/post/"
  weight = -100

[[menu.main]]
  identifier = "contact"
  name = "Say Hi"
  title = "Contact section"
  url = "/contact/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false